Added log button and Trignometric Inverse Functions
elementary/calculator pull request #140
Opened 2020-09-23 09:20 UTC by techimanshu8

I have added log button for both log 2 base 10 and normal log .
And added sin , cos and tan inverse functions . also added a inverse function to calculate 1/X .
I had also included test for these
![Screenshot from 2020-09-23 14-49-14](https://user-images.githubusercontent.com/66455348/93993137-00551680-fdac-11ea-8dc5-456010b374df.png)

2020-09-23 14:59 UTC, jeremypw commented
Tip:  You can make this a Draft review if you are still working it :smile:

2020-09-23 15:38 UTC, techimanshu8 commented
> Tip: You can make this a Draft review if you are still working it
@jeremypw  Thanks for suggestion but I have done all , now This is ready for review .

2020-09-25 03:11 UTC, techimanshu8 commented
Resolves #139

2020-09-30 16:26 UTC, jeremypw requested changes
Thanks for providing this!  It works well and in general looks good.  Just a few minor issues noted in line.

2020-09-30 16:26 UTC, jeremypw commented on src/MainWindow.vala
> +            var button_inverse = new Button ("X<sup>-1</sup>");
In line with other button labels this should have a lowercase 'x'.

2020-09-30 16:30 UTC, jeremypw commented on src/MainWindow.vala
> +            var button_atan = new Button ("tan<sup>-1</sup>", _("arc tangent"));
The tooltips should be in title case:  "Logarithm Base 10", "Natural Logarithm", "Inverse Sine", "Inverse Cosine", "Inverse Tangent".   ("Arcsine", "Arccosine" and "Arctangent" are also OK)

2020-09-30 16:50 UTC, jeremypw commented
Another thing you will need to do is update the appdata file in `\data` for the next release. As there is a new functionality make it v 1.6.0.
```
    <release version="1.6.0" date="2020-05-17" urgency="medium">
      <description>
        <p>Improvements:</p>
        <ul>
          <li>Add log and inverse trigonometric functions</li>
        </ul>
      </description>
    </release>
```

2020-10-01 16:18 UTC, jeremypw commented
@techimanshu8 Unfortunately this is failing one of the Core tests - could you look into it? Thanks

2020-10-01 16:27 UTC, jeremypw commented
Hmm - looks like the faulty line is not due to this PR - it is line 75 in CoreTest.vala.  Not sure how that got into master :disappointed:  For convenience could you fix it here?  It should be: `assert_equal ("10^(log(2.2))", "2.2");` I suppose.

2020-10-01 16:38 UTC, jeremypw commented
Ah, I see you changed the definition of "log" for evaluation.  I think maybe the button should be labelled ""log<sub>10</sub>" to make this clear.

2020-10-02 03:28 UTC, techimanshu8 commented
Ya, Sure  we can change label , but   I had also changed Coretest.vala accordingly but don`t know why it is not considering.

2020-10-02 09:04 UTC, jeremypw commented
As far as I can tell, you added some new lines to CoreTest.vala (which are fine) but one of the existing tests started failing because you redefined `log` elsewhere.  Previously `log` was interpreted as log<sub>e</sub>.  Now it is interpreted as log<sub>10</sub>.  So the test which is now on line 75 needs updating as indicated above.

2020-10-02 16:04 UTC, jeremypw approved these changes
Good to go - thanks!

2020-10-02 16:04 UTC, merged